<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>KintoneNetLibrary</RootNamespace>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KintoneNetLibrary</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="AbskintoneModel.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="tests\" />
  </ItemGroup>
</Project>