using System.Text;
using KintoneNetLibrary.CodeGen.Application.Interfaces;
using KintoneNetLibrary.CodeGen.Domain.Models;
using KintoneNetLibrary.CodeGen.Domain.Options;
using KintoneNetLibrary.CodeGen.Domain.Schemas;
using Microsoft.Extensions.Logging;

namespace KintoneNetLibrary.CodeGen.Application.Emitters;

public class PythonCodeEmitter(INameConverter names, ITypeMapper types, ILogger<PythonCodeEmitter> logger) : ICodeEmitter {
    private readonly INameConverter _names = names;
    private readonly ITypeMapper _types = types;
    private readonly ILogger<PythonCodeEmitter> _logger = logger;

    public GeneratedModelResult Emit(KintoneAppSchema schema, CodeEmitterOptions options) {
        var sb = new StringBuilder();

        // モジュールヘッダ
        sb.AppendLine("# Generated by kmodel");
        sb.AppendLine($"# AppId: {schema.AppId}");
        sb.AppendLine();

        // メインクラス
        this.EmitMainClass(sb, schema);

        // サブテーブル
        foreach (var sub in schema.SubTables) {
            this.EmitSubTable(sb, sub);
        }

        return new GeneratedModelResult {
            MainModelCode = sb.ToString(),
            // ClassName = this._names.ToClassName(schema.AppName, ""),
            Revision = schema.Revision
        };
    }

    private void EmitMainClass(StringBuilder sb, KintoneAppSchema schema) {
        var className = this._names.ToClassName(schema.AppName, "");
        sb.AppendLine($"class {className}:");

        foreach (var field in schema.Fields) {
            var propName = this._names.ToPropertyName(field.Label, field.FieldCode);
            var typeName = this.MapPythonType(field);

            sb.AppendLine($"    {propName}: {typeName}");
        }

        sb.AppendLine();
    }

    private void EmitSubTable(StringBuilder sb, KintoneSubTableSchema sub) {
        var className = this._names.ToClassName(sub.FieldCode, "");
        sb.AppendLine($"class {className}:");

        foreach (var field in sub.Fields) {
            var propName = this._names.ToPropertyName(field.Label, field.FieldCode);
            var typeName = this.MapPythonType(field);

            sb.AppendLine($"    {propName}: {typeName}");
        }

        sb.AppendLine();
    }

    private string MapPythonType(KintoneFieldSchema field) {
        return field.FieldType switch {
            "SINGLE_LINE_TEXT" => "str",
            "NUMBER" => "str", // Kintone の number は文字列で返ることが多い
            "DATE" => "str",
            "DATETIME" => "str",
            "USER_SELECT" => "dict",
            "SUBTABLE" => $"list[{this._names.ToClassName(field.FieldCode, "")}]",
            _ => "str"
        };
    }
}