using System.Text;
using KintoneNetLibrary.CodeGen.Application.Interfaces;
using KintoneNetLibrary.CodeGen.Domain.Enums;
using KintoneNetLibrary.CodeGen.Domain.Models;
using KintoneNetLibrary.CodeGen.Domain.Options;
using KintoneNetLibrary.CodeGen.Domain.Schemas;
using KintoneNetLibrary.CodeGen.Infrastructure.Services;
using KintoneNetLibrary.Domain.Enums;
using KintoneNetLibrary.Domain.Interfaces;
using KintoneNetLibrary.Infrastructure.Helpers;
using Microsoft.Extensions.Logging;

namespace KintoneNetLibrary.CodeGen.Application.Emitters;

/// <summary>
/// Python コードエミッター
/// </summary>
/// <param name="converterFactory">名前変換ファクトリー</param>
/// <param name="mapperFactory">型マッパーファクトリー</param>
/// <param name="clock">日時プロバイダー</param>
/// <param name="logger">ロガー</param>
public class PythonCodeEmitter(
    // INameConverterFactory converterFactory,
    // INameConverter nameConverter,
    ITypeMapperFactory mapperFactory,
    IDateTimeProvider? clock = null,
    ILogger<PythonCodeEmitter>? logger = null) : ICodeEmitter {

    // private readonly INameConverter _converter = converterFactory.Create(GenerateLanguages.Python);
    private INameConverter _converter;
    private readonly ITypeMapper _mapper = mapperFactory.Create(GenerateLanguages.Python);
    private readonly IDateTimeProvider _clock = clock ?? new SystemDateTimeProvider();
    private readonly ILogger<PythonCodeEmitter>? _logger = logger;
    private readonly string _invalid_field_name = "INVALID_FIELD_NAME";

    /// <summary>
    /// 対応する生成言語
    /// </summary>
    public GenerateLanguages Language => GenerateLanguages.Python;

    public void SetNameConverter(INameConverter converter) {
        this._converter = converter;
    }

    /// <summary>
    /// コード生成を実行します
    /// </summary>
    /// <param name="schema">Kintone アプリスキーマ</param>
    /// <param name="options">コードエミッターオプション</param>
    /// <returns>生成されたモデル結果</returns>
    public GeneratedModelResult Emit(KintoneAppSchema schema, CodeEmitterOptions options) {
        this._logger?.LogInformation("Starting Python code emission for App ID: {AppId}", schema.AppId);

        try {
            var pyOptions = (PythonEmitterOptions)options;
            var sb = new StringBuilder();

            // ヘッダ
            this.GenerateHeader(sb, schema, pyOptions);

            // imports
            this.EmitImports(sb, schema);

            // 組み込み型
            this.EmitBuiltInTypes(sb);

            // メインクラス
            this.EmitMainClass(sb, schema, pyOptions);

            // サブテーブル
            foreach (var subTable in schema.SubTables) {
                this.EmitSubTable(sb, subTable, pyOptions);
            }

            return new GeneratedModelResult {
                MainModelCode = sb.ToString(),
                Revision = schema.Revision
            };

        } finally {
            this._logger?.LogInformation("Completed Python code emission for App ID: {AppId}", schema.AppId);
        }
    }

    /// <summary>
    /// ヘッダを生成する
    /// </summary>
    /// <param name="sb">文字列ビルダー</param>
    /// <param name="schema">Kintone アプリスキーマ</param>
    /// <param name="options">Python エミッターオプション</param>
    private void GenerateHeader(StringBuilder sb, KintoneAppSchema schema, PythonEmitterOptions options) {
        sb.AppendLine("# -----------------------------------------------------------------------------");
        sb.AppendLine("# This file was automatically generated by kmodel.");
        sb.AppendLine("# Do not edit this file directly. Your changes may be overwritten.");
        sb.AppendLine("#");
        var appName = this._converter.ToClassName(schema.AppName, schema.AppId.ToString());
        // sb.AppendLine($"# App Name : {appName}");
        sb.AppendLine($"# App Name : {schema.AppName}");
        sb.AppendLine($"# App ID   : {schema.AppId}");
        sb.AppendLine($"# Revision : {schema.Revision}");
        sb.AppendLine($"# Module   : {options.ModuleName}");
        sb.AppendLine($"# Generated: {this._clock.UtcNow:s} (UTC)");
        if (!string.IsNullOrWhiteSpace(options.HeaderComment)) {
            sb.AppendLine($"# {options.HeaderComment}");
        }
        sb.AppendLine("# -----------------------------------------------------------------------------");
        sb.AppendLine();
    }

    /// <summary>
    /// メインクラスを出力する
    /// </summary>
    /// <param name="sb">文字列ビルダー</param>
    /// <param name="schema">Kintone アプリスキーマ</param>
    /// <param name="options">Python エミッターオプション</param>
    private void EmitMainClass(StringBuilder sb, KintoneAppSchema schema, PythonEmitterOptions options) {
        var className = this._converter.ToClassName(schema.AppName, schema.AppId.ToString());

        sb.AppendLine("@dataclass");
        sb.AppendLine($"class {className}:");

        var fields = schema.Fields.Where(f => !SystemFieldService.IsSystemField(f));

        if (!fields.Any()) {
            sb.AppendLine("    pass");
            sb.AppendLine();
            return;
        }

        foreach (var field in fields) {
            var propName = this._converter.ToPropertyName(field.Label, field.FieldCode);
            var typeName = this._mapper.MapType(field, options.UseTypeHint);

            this.EmitField(sb, field, typeName, propName);
        }
    }

    /// <summary>
    /// import セクションを出力する
    /// </summary>
    /// <param name="sb">文字列ビルダー</param>
    /// <param name="schema">Kintone アプリスキーマ</param>
    private void EmitImports(StringBuilder sb, KintoneAppSchema schema) {
        sb.AppendLine("from dataclasses import dataclass");
        if (schema.Fields.Any(f => f.FieldType == KintoneFieldType.Date || f.FieldType == KintoneFieldType.DateTime || f.FieldType == KintoneFieldType.Time)) {
            sb.AppendLine("import datetime");
        }
        sb.AppendLine();
    }
    /// <summary>
    /// サブテーブルを出力する
    /// </summary>
    /// <param name="sb">文字列ビルダー</param>
    /// <param name="subTable">Kintone サブテーブルスキーマ</param>
    /// <param name="options">Python エミッターオプション</param>
    private void EmitSubTable(StringBuilder sb, KintoneSubTableSchema subTable, PythonEmitterOptions options) {
        var className = this._converter.ToClassName(subTable.Label, subTable.FieldCode);

        sb.AppendLine("@dataclass");
        sb.AppendLine($"class SubTable{className}:");

        if (!subTable.Fields.Any()) {
            sb.AppendLine("    pass");
            sb.AppendLine();
            return;
        }

        foreach (var field in subTable.Fields) {
            var propName = this._converter.ToPropertyName(field.Label, field.FieldCode);
            var typeName = this._mapper.MapType(field, options.UseTypeHint, $"SubTable{className}");

            this.EmitField(sb, field, typeName, propName);
        }
    }
    /// <summary>
    /// フィールドを出力する
    /// </summary>
    /// <param name="sb">文字列ビルダー</param>
    /// <param name="field">Kintone フィールドスキーマ</param>
    /// <param name="typeName">型名</param>
    /// <param name="propName">プロパティ名</param>
    private void EmitField(StringBuilder sb, KintoneFieldSchema field, string typeName, string propName) {
        // コメント
        sb.AppendLine($"    # Label: {field.Label}");
        sb.AppendLine($"    # FieldCode: {field.FieldCode}");

        if (field.Options?.Any() == true) {
            var opts = string.Join(", ", field.Options.OrderBy(o => o).Select(o => $"\"{o}\""));
            sb.AppendLine($"    # Options: [{opts}]");
        }

        // 変換失敗
        if (propName == this._invalid_field_name) {
            sb.AppendLine("    # TODO: フィールド名を変換できませんでした。手動で修正してください。");
            sb.AppendLine($"    {propName}: {typeName}");
            sb.AppendLine();
            return;
        }

        // 通常フィールド
        sb.AppendLine($"    {propName}: {typeName}");
        sb.AppendLine();
    }
    /// <summary>
    /// 組み込み型を出力する
    /// </summary>
    /// <param name="sb">文字列ビルダー</param>
    private void EmitBuiltInTypes(StringBuilder sb) {
        sb.AppendLine("# -----------------------------------------------------------------------------");
        sb.AppendLine("# Kintone built-in types (auto-generated)");
        sb.AppendLine("# -----------------------------------------------------------------------------");
        sb.AppendLine("# File");
        sb.AppendLine("@dataclass");
        sb.AppendLine("class File:");
        sb.AppendLine("    fileKey: str");
        sb.AppendLine("    name: str");
        sb.AppendLine("    contentType: str");
        sb.AppendLine("    size: int");
        sb.AppendLine();

        sb.AppendLine("# User");
        sb.AppendLine("@dataclass");
        sb.AppendLine("class User:");
        sb.AppendLine("    code: str");
        sb.AppendLine("    name: str");
        sb.AppendLine();

        sb.AppendLine("# Group");
        sb.AppendLine("@dataclass");
        sb.AppendLine("class Group:");
        sb.AppendLine("    code: str");
        sb.AppendLine("    name: str");
        sb.AppendLine();

        sb.AppendLine("# Organization");
        sb.AppendLine("@dataclass");
        sb.AppendLine("class Organization:");
        sb.AppendLine("    code: str");
        sb.AppendLine("    name: str");
        sb.AppendLine("# -----------------------------------------------------------------------------");
        sb.AppendLine();
    }
}
