using System.Text;
using KintoneNetLibrary.CodeGen.Application.Interfaces;
using KintoneNetLibrary.CodeGen.Domain.Enums;
using KintoneNetLibrary.CodeGen.Domain.Models;
using KintoneNetLibrary.CodeGen.Domain.Options;
using KintoneNetLibrary.CodeGen.Domain.Schemas;
using Microsoft.Extensions.Logging;

namespace KintoneNetLibrary.CodeGen.Application.Emitters;

/// <summary>
/// Python コードエミッタ
/// </summary>
/// <param name="converterFactory"></param>
/// <param name="mapperFactory"></param>
public class PythonCodeEmitter(
    INameConverterFactory converterFactory,
    ITypeMapperFactory mapperFactory,
    ILogger<PythonCodeEmitter>? logger = null) : ICodeEmitter {
    private readonly INameConverter _converter = converterFactory.Create(GenerateLanguages.Python);
    private readonly ITypeMapper _mapper = mapperFactory.Create(GenerateLanguages.Python);
    private readonly ILogger<PythonCodeEmitter>?_logger = logger;

    public GeneratedModelResult Emit(KintoneAppSchema schema, CodeEmitterOptions options) {
        var sb = new StringBuilder();

        // ヘッダ
        sb.AppendLine("# Generated by kmodel");
        sb.AppendLine($"# AppId: {schema.AppId}");
        sb.AppendLine($"# Revision: {schema.Revision}");
        sb.AppendLine();

        // メインクラス
        this.EmitMainClass(sb, schema);

        // サブテーブル
        foreach (var subTable in schema.SubTables) {
            this.EmitSubTable(sb, subTable);
        }

        return new GeneratedModelResult {
            MainModelCode = sb.ToString(),
            Revision = schema.Revision
        };
    }

    private void EmitMainClass(StringBuilder sb, KintoneAppSchema schema) {
        var className = this._converter.ToClassName(schema.AppName, "");
        sb.AppendLine($"class {className}:");

        if (schema.Fields.Count == 0) {
            sb.AppendLine("    pass");
            sb.AppendLine();
            return;
        }

        foreach (var field in schema.Fields) {
            var propName = this._converter.ToPropertyName(field.Label, field.FieldCode);
            var typeName = this._mapper.MapType(field, false);

            sb.AppendLine($"    {propName}: {typeName}");
        }

        sb.AppendLine();
    }

    private void EmitSubTable(StringBuilder sb, KintoneSubTableSchema subTable) {
        var className = this._converter.ToClassName(subTable.FieldCode, "");
        sb.AppendLine($"class {className}:");

        if (subTable.Fields.Count == 0) {
            sb.AppendLine("    pass");
            sb.AppendLine();
            return;
        }

        foreach (var field in subTable.Fields) {
            var propName = this._converter.ToPropertyName(field.Label, field.FieldCode);
            var typeName = this._mapper.MapType(field, false);

            sb.AppendLine($"    {propName}: {typeName}");
        }

        sb.AppendLine();
    }
}
